name: Node.js Package

on:
  push:
    tags:
      - '**-next*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@bernardocorbella'
      - name: Cache
        uses: actions/cache@v1.0.2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build
      - run: yarn ci
      - run: yarn publish:next
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
